apiVersion: v1
clusters:
- cluster:
    server: # EKS cluster URI
    certificate-authority-data: # cert 
  name: # EKS Cluster ARN
contexts:
- context:
    cluster: # EKS Cluster ARN
    user: # EKS Cluster ARN
  name: # context-name
current-context: # context-name 
kind: Config
preferences: {}
users:
- name: # EKS Cluster ARN
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws
      args:
        - eks
        - get-token
        - --cluster-name
        - # cluster name
